version: "3.3"
services:
  myapp:
    image: myapp
    restart: always
    volumes:
      - ./myapp/myapp-config:/config/myapp-config
      - ./wait-for-it/wait-for-it.sh:/startup/wait-for-it.sh
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      - mysql
      - vkmock
    entrypoint:
      - /startup/wait-for-it.sh
      - mysql:3036
      - --
      - ./myapp
      - --config=/config/myapp-config

  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example

  vkmock:
    build: mock
    restart: always
    expose:
      - 5000
    ports:
      - 5000:5000

  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network" ,"final-project_default"]
    ports:
      - "4444:4444"
